import json
from fpdf import FPDF
from datetime import datetime
import os

def generate_pdf_report(data_file="roster_data.json", output_file=None, user_info=None):
    """
    Generates a PDF report from a JSON data file using fpdf2.
    
    The JSON file should contain a list of roster records.
    """
    
    if not os.path.exists(data_file):
        print(f"Error: Data file not found at {data_file}")
        return

    try:
        with open(data_file, 'r') as f:
            data = json.load(f)
            roster_data = data.get('records', [])
    except json.JSONDecodeError:
        print(f"Error: Could not decode JSON from {data_file}")
        return

    if not roster_data:
        print("No records to generate a report.")
        return

    pdf = FPDF(orientation='L', unit='mm', format='A4')
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # Set up fonts and colors
    pdf.set_font('Arial', 'B', 16)
    pdf.set_text_color(31, 41, 55) # Dark Gray

    # Title
    pdf.cell(0, 10, 'Jail Roster Report', 0, 1, 'C')

    # Header Info
    pdf.set_font('Arial', '', 10)
    user_name = user_info.get('name', 'N/A') if user_info else 'N/A'
    user_role = user_info.get('role', 'N/A').capitalize() if user_info else 'N/A'
    
    pdf.cell(0, 5, f"Generated By: {user_name} ({user_role})", 0, 0, 'L')
    pdf.cell(0, 5, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}", 0, 1, 'R')
    pdf.cell(0, 5, f"Total Records: {len(roster_data)}", 0, 1, 'L')
    pdf.ln(5)

    # Table Header
    pdf.set_fill_color(243, 244, 246) # Light Gray
    pdf.set_text_color(75, 85, 99) # Medium Gray
    pdf.set_font('Arial', 'B', 8)
    
    col_widths = [10, 30, 20, 10, 25, 25, 60, 60]
    headers = ['Cell', 'Name', 'DOB', 'Sex', 'OCA #', 'Arrest Date', 'Charges', 'Holders / Notes']
    
    for i, header in enumerate(headers):
        pdf.cell(col_widths[i], 7, header, 1, 0, 'C', 1)
    pdf.ln()

    # Table Data
    pdf.set_font('Arial', '', 8)
    pdf.set_text_color(0, 0, 0) # Black

    for record in roster_data:
        # Determine status for background color (simple visual cue)
        fill = False
        if record.get('releaseDateTime'):
            pdf.set_fill_color(254, 243, 199) # Yellow-ish for Released
            fill = True
        elif record.get('courtDate'):
            pdf.set_fill_color(219, 234, 254) # Blue-ish for Court Scheduled
            fill = True
        else:
            pdf.set_fill_color(255, 255, 255) # White for In Custody

        sex = 'M' if record.get('sexM') else ('F' if record.get('sexF') else '-')
        
        row_data = [
            record.get('cell', ''),
            record.get('name', ''),
            record.get('dob', ''),
            sex,
            record.get('ocaNumber', ''),
            record.get('arrestDateTime', ''),
            record.get('charges', ''),
            record.get('holdersNotes', '')
        ]

        # MultiCell for wrapping text in cells
        # Calculate max height of the row
        max_height = 7
        for i, data in enumerate(row_data):
            # Use a temporary PDF object for dry run to avoid state changes
            temp_pdf = FPDF(orientation='L', unit='mm', format='A4')
            temp_pdf.set_font('Arial', '', 8)
            lines = temp_pdf.multi_cell(col_widths[i], 3.5, data, 0, 'L', 0, 0, align='L', dry_run=True)
            max_height = max(max_height, lines * 3.5)
        
        # Draw the cells
        x_start = pdf.get_x()
        y_start = pdf.get_y()
        
        for i, data in enumerate(row_data):
            pdf.multi_cell(col_widths[i], max_height, data, 1, 'L', fill, 0, x=x_start, y=y_start, align='L')
            x_start += col_widths[i]
        
        pdf.ln(max_height)

    # Output PDF
    if output_file is None:
        output_file = f"jail_roster_report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf"
        
    pdf.output(output_file)
    print(f"Successfully generated PDF report: {output_file}")

if __name__ == '__main__':
    # Example usage:
    # 1. Export data from the web app using the "Export Data (JSON)" button.
    # 2. Save the downloaded JSON file as 'roster_data.json' in the same directory.
    # 3. Run this script: python3 generate_pdf_report.py
    
    # Dummy user info for the report header
    dummy_user = {'name': 'System Admin', 'role': 'Administrator'}
    
    # Create a dummy JSON file if it doesn't exist for testing the script
    if not os.path.exists("roster_data.json"):
        dummy_data = {
            "export_date": datetime.now().isoformat(),
            "total_records": 1,
            "records": [{
                "id": "1", "cell": "A1", "dayNumber": "1", "totalNumber": "1", 
                "name": "Smith, John D", "dob": "1985-05-10", "ssn": "XXX-XX-XXXX", 
                "sexM": True, "sexF": False, "ocaNumber": "SHPD2025-001", 
                "arrestDateTime": "10/10/2025 @ 1000", "misdemeanor": False, 
                "felony": True, "charges": "Aggravated Assault, Resisting Arrest", 
                "courtPacket": "Y", "inst": "N", "courtCaseTicket": "C-12345", 
                "bondChangeNotice": False, "bond": "$50,000", "waiver": "None", 
                "courtDate": "2025-11-01", "releaseDateTime": "", 
                "holdersNotes": "Federal Hold", "chargingDocs": "Filed"
            }]
        }
        with open("roster_data.json", "w") as f:
            json.dump(dummy_data, f, indent=4)
            
    generate_pdf_report(user_info=dummy_user)
